//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MagicLantern
{
    [Serializable]
    public class FrameMsg : Message
    {
        public const string k_RosMessageName = "magic_lantern_msgs/Frame";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains an uncompressed image
        //  (0, 0) is at top-left corner of image
        // 
        public uint height;
        //  image height, that is, number of rows
        public uint width;
        //  image width, that is, number of columns
        public byte[] data;
        //  actual matrix data, size is (step * rows)

        public FrameMsg()
        {
            this.height = 0;
            this.width = 0;
            this.data = new byte[0];
        }

        public FrameMsg(uint height, uint width, byte[] data)
        {
            this.height = height;
            this.width = width;
            this.data = data;
        }

        public static FrameMsg Deserialize(MessageDeserializer deserializer) => new FrameMsg(deserializer);

        private FrameMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.height);
            deserializer.Read(out this.width);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.height);
            serializer.Write(this.width);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "FrameMsg: " +
            "\nheight: " + height.ToString() +
            "\nwidth: " + width.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
